# Testing correctness of XML files only.

notifications:
  email: false

language: python

python:
  - "2.7"

install:
  - "sudo apt-get install libxml2-utils"

script:
  - "xmllint --noout invenio_opendata/testsuite/data/*/*.xml"
